[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fortunes"
version = "0.1.0"
description = "Fortunes package"
readme = "README.md"
authors = [
    { name = "Yuhao Sheng", email = "ys4689@nyu.edu" },
]
license = { text = "MIT" }
dependencies = [
    "python-dotenv",
]
requires-python = ">=3.10, <4.0"

[tool.setuptools]
packages = ["fortunes"]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = ["pytest"]